<?php

/**
 * @file
 * Islandora pdf solution pack module
 */
define('ISLANDORA_PDF_SP_MODS_FORM_NAME', 'Islandora PDF MODS Form');

/**
 * islandora pdf sp required fedora objects
 * @return type 
 */
function islandora_pdf_sp_required_fedora_objects() {
  module_load_include('inc', 'fedora_repository', 'fedora_repository.solutionpacks');

  // Add the form and associate it to the content model
  $module_path = drupal_get_path('module', 'islandora_pdf_sp');
  $form_name = 'Islandora PDF MODS Form';
  $form_xml = file_get_contents("$module_path/xml/mods_pdf.xml");
  solution_pack_add_form($form_name, $form_xml);
  solution_pack_add_form_association('islandora:sp_strict_pdf', $form_name);

  return array(
    'islandora_pdf_sp' => array(
      'module' => 'islandora_pdf_sp',
      'title' => 'Islandora PDF Solution Pack',
      'objects' => array(
        array(
          'pid' => 'islandora:sp_strict_pdf',
          'label' => 'Islandora strict PDF content model',
          'dsid' => 'ISLANDORACM',
          'datastream_file' => "$module_path/xml/STRICT_SP_PDFCM.xml",
          'cmodel' => 'fedora-system:ContentModel-3.0',
        ),
        array(
          'pid' => 'islandora:sp_pdf_collection',
          'label' => 'Islandora PDF Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => variable_get('fedora_repository_pid', 'islandora:root'),
          'datastreams' => array(
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/images/Crystal_Clear_filesystem_folder_grey.png",
              'mimetype' => 'image/png',
            ),
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/PDF-COLLECTION POLICY.xml",
            ),
          ),
        ),
      ),
    ),
  );
}

