<?php

/**
 * @file
 *
 * Handles the creation/display of islandora:sp-pdf objects.
 */

/**
 * Implements hook_menu().
 */
function islandora_pdf_menu() {
  return array(
    'admin/islandora/pdf' => array(
      'title' => 'PDF Module',
      'description' => 'Configure the PDF solution pack.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_pdf_admin'),
      'file' => 'admin/islandora_pdf.admin.inc',
      'type' => MENU_NORMAL_ITEM,
    )
  );
}

/**
 * Implements hook_theme().
 */
function islandora_pdf_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_pdf' => array(
      'file' => 'theme/islandora_pdf.theme.inc',
      'template' => 'theme/islandora-pdf',
      'pattern' => 'islandora_pdf__',
      'variables' => array('islandora_object' => NULL),
    )
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_pdf_islandora_required_objects() {
  $module_path = drupal_get_path('module', 'islandora_pdf');
  return array(
    'islandora_pdf' => array(
      'title' => 'Islandora PDF',
      'objects' => array(
        array(
          'pid' => 'islandora:sp_pdf',
          'label' => 'Islandora PDF content model',
          'cmodel' => 'fedora-system:ContentModel-3.0',
          'datastreams' => array(
            array(
              'dsid' => 'DS-COMPOSITE-MODEL',
              'label' => 'DS-COMPOSITE-MODEL',
              'mimetype' => 'text/xml',
              'control_group' => 'X',
              'datastream_file' => "$module_path/xml/islandora_pdf_ds_composite_model.xml",
            ),
          ),
        ),
        array(
          'pid' => 'islandora:sp_pdf_collection',
          'label' => 'PDF collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:root',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'label' => 'Collection policy',
              'mimetype' => 'text/xml',
              'control_group' => 'X',
              'datastream_file' => "$module_path/xml/islandora_pdf_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'label' => 'Thumbnail',
              'mimetype' => 'image/png',
              'control_group' => 'M',
              'datastream_file' => "$module_path/images/folder.png",
            ),
          ),
        ),
      ),
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_pdf_islandora_sp_pdf_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_pdf', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_ingest_post_ingest().
 */
function islandora_pdf_islandora_sp_pdf_islandora_ingest_post_ingest($object) {
  module_load_include('inc', 'islandora_pdf', 'includes/pdf.process');
  islandora_pdf_create_all_derivatives($object);
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_pdf_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_pdf');
  return array(
    'PDF MODS form' => array(
      'form_file' => "$module_path/xml/islandora_pdf_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_pdf_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_pdf_mods_form' => array(
      'content_model' => 'islandora:sp_pdf',
      'form_name' => 'PDF MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_pdf_islandora_sp_pdf_islandora_ingest_steps(array $configuration) {
  return array(
    'islandora_pdf_file_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_pdf_pdf_upload_form',
      'module' => 'islandora_pdf',
      'file' => 'includes/pdf_upload.form.inc'
    )
  );
}
